version: '3.8'

services:
  tidbyt-server:
    image: tidbyt-server
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 server:app
    tty: true
    stdin_open: true
